# Generated by Django 4.2 on 2023-06-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_core_level_boost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='power',
        ),
        migrations.AlterField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
