# Generated by Django 4.2 on 2023-06-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_boost_power_alter_boost_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='coins',
            field=models.IntegerField(default=1000),
        ),
    ]
