# Generated by Django 4.2 on 2023-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_core_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
